repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.17  # run `pre-commit autoupdate` to pin to latest
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
